import PrototypeNav, { Footer } from "@/components/PrototypeNav";

const principles = [
  ["01", "Sovereignty by design", "Make control, boundaries, and dependencies design inputs from the beginning."],
  ["02", "Privacy with purpose", "Collect and expose only what the workflow requires, with an understandable reason."],
  ["03", "Human responsibility remains visible", "Keep review, escalation, and ownership legible when uncertainty or consequence rises."],
  ["04", "Traceability over black-box convenience", "Make relevant context, versions, inputs, and decision paths inspectable."],
  ["05", "Graceful failure is part of the design", "Define what happens when a model, service, network, or integration is unavailable."],
  ["06", "Evidence before scale", "Let context-specific validation precede larger investment or operational trust."],
];

const risks = [
  ["Data risk", "What information must remain within your operational, organizational, or geographic boundary?"],
  ["Model risk", "What happens when a model is uncertain, changes behavior, or is unavailable?"],
  ["Workflow risk", "Which decisions require a human owner, a second review, or escalation?"],
  ["Operational risk", "How should the workflow behave during outage, latency, or partial failure?"],
  ["Governance risk", "Who can approve, change, pause, inspect, or roll back the system?"],
  ["Adoption risk", "Will people understand the system’s role, limits, and escalation behavior?"],
];

export default function Principles() {
  return <div className="min-h-screen bg-[#0A0F2C] text-slate-100"><PrototypeNav /><main>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mono text-cyan-300">PRINCIPLES / RISK POSTURE</div><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white md:text-7xl">Trust is not a feature. It is a <span className="text-cyan-300">system property.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Sovereign Technology is the ability of an organization to understand, govern, and change the systems it depends on.</p></section>
    <section className="border-t border-cyan-300/15"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><div className="mono text-cyan-300">OPERATING PRINCIPLES</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-white">Make control visible.</h2></div><div className="grid border-t-2 border-cyan-300 md:grid-cols-2">{principles.map(([number,title,body])=><article key={number} className="border-b border-cyan-300/20 p-5 md:odd:border-r"><div className="mono text-fuchsia-300">{number}</div><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p></article>)}</div></div></div></section>
    <section className="border-t border-cyan-300/15"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><div className="mono text-cyan-300">RISK INPUTS</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-white">Risk is a design input, not a compliance appendix.</h2></div><div className="grid gap-8 md:grid-cols-2">{risks.map(([title,question])=><article key={title} className="border-t border-fuchsia-300/60 pt-4"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{question}</p></article>)}</div></div></div></section>
    <section className="border-t border-cyan-300/15"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><div className="mono text-cyan-300">DECISION RIGHTS</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-white">A system is not sovereign without ownership.</h2></div><div className="border-t-2 border-cyan-300">{["Use-case approval / Business or workflow owner","Data boundary / Data, privacy, or information owner","Architecture / Technology or security owner","Human review / Workflow owner with risk input","Pause or rollback / Operational owner","Scale decision / Executive sponsor + available evidence"].map((row,index)=>{const [a,b]=row.split(" / ");return <div key={a} className="grid grid-cols-[1fr_1fr] gap-5 border-b border-cyan-300/20 py-4"><span className="text-sm text-slate-100"><span className="mono mr-4 text-fuchsia-300">0{index+1}</span>{a}</span><span className="text-sm text-slate-400">{b}</span></div>})}</div></div></div></section>
    <section className="border-t border-cyan-300/15"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><div className="mono text-cyan-300">EVIDENCE LADDER</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-white">Evidence earns the right to scale.</h2></div><div className="grid border-b-2 border-cyan-300 md:grid-cols-5">{["Principle","Method","Artifact","Validation","Approved evidence"].map((item,index)=><div key={item} className="border-t border-cyan-300/50 p-4 md:border-r md:last:border-r-0"><div className="mono text-fuchsia-300">0{index+1}</div><h3 className="mt-10 text-lg font-semibold">{item}</h3><p className="mt-3 text-xs leading-5 text-slate-400">{index===0?"What should guide the work.":index===1?"How principles shape engineering.":index===2?"What can be inspected and revisited.":index===3?"How the system is tested in context.":"A publishable outcome with context and permission."}</p></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="border border-cyan-300/30 p-8 md:p-12"><div className="mono text-cyan-300">EVIDENCE BOUNDARY</div><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.04em] text-white">A prototype is not proof of production readiness.</h2><p className="mt-5 max-w-2xl leading-7 text-slate-400">This prototype does not claim customer outcomes, certifications, security guarantees, or production assurance. What is illustrative, validated, and unproven should remain explicit.</p></div></section>
  </main><Footer /></div>;
}
